export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const FETCH_ACCOUNT_TRANSACTION_REQUEST = 'FETCH_ACCOUNT_TRANSACTION_REQUEST';
export const FETCH_USER_ACCOUNTS = 'FETCH_USER_ACCOUNTS';
